branch-defaults:
  main:
    environment: ads-python-cd-env
    group_suffix: null
global:
  application_name: ads-python-cd
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Python 3.8
  default_region: sa-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application